# settings.ini

[telegram]
bot_api=
bot_id=7822548219
group_id=-1002303730662
base_group_id=-1002497585408

[crypto_parser]
triger_crypto_signal=4
triger_delay_crypto=5
crypto_key=https://api.binance.com/api/v3/ticker/price?symbol=
delay_commands=0.3
crypto_valutes=BTCUSDT,ETHUSDT,SOLUSDT,XRPUSDT,TONUSDT,DOGEUSDT,TRUMPUSDT
char_code_currency=USD
name_file=crypto_bot